ceph/mita

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

change keyname to 'jenkins-build' in the node configuration

---

mita/controllers/nodes.py
mita/tests/config.py
mita/tests/functional/controllers/test_nodes.py

The checks for `idle_since` where backwards and checking the wrong thing. Added some tests as well.

Idle since fixes

---

mita/async.py

fix a bug in asnyc.check_idling where the uuid var was not defined

---

mita/util.py

really get the node labels before trying to match

---

deploy/playbooks/roles/common/templates/prod.py.j2

fix the root logger config that spits out double logging

---

mita/expressions.py
mita/tests/unit/test_expressions.py
mita/util.py

Initial take on a very simple/dumb label expression expander helper. Just so we can parse the weird notation that Jenkins offers.

Expressions

---

mita/util.py

from_label might have a label expression

---

mita/async.py

prevent jenkins not found exceptions break async task

---

mita/async.py
mita/util.py

Seems like there is a new PEP8 thing about assignments for lambda expressions, that is why I ended up using def lines.

Is it really stuck?

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

define two new nodes to allow unique node creation

---

mita/controllers/nodes.py
mita/tests/config.py
mita/tests/conftest.py
mita/tests/functional/controllers/test_nodes.py

We should prevent breakage when trying to delete from Jenkins. Adds more tests too.

Robust deletion

---

mita/controllers/nodes.py

provide a bit more information when creating a new node

---

README.rst
deploy/playbooks/deploy_vagrant.yml
deploy/playbooks/roles/common/templates/prod_nodes.py.j2
mita/providers/openstack.py

This is lacking docs and tests, but I've manually tested both the volume creation and deletion.

adds volume creation and deletion

---

mita/providers/openstack.py

Fixes a bunch of unsafe logging usage and provides a safer way to detect volumes that may not be available.

Volume logging

---

mita/async.py
mita/controllers/nodes.py
mita/util.py

allow to delay the node deletion

---

mita/providers/openstack.py

check the state of the volume in delete_volume to ensure it exists

---

deploy/playbooks/roles/common/templates/prod.py.j2

mita doesn't render anything, no need for templates

---

mita/controllers/nodes.py

I swear this is the last time we deal with JSON like this in this
app. Next time we need to start implementing Notario

handle invalid or non-existing json

---

mita/hooks/error.py

give more information on error

---

mita/controllers/nodes.py

tasks need to consume a tuple not a single arg

---

mita/async.py

configure the celery worker once at init

---

mita/tasks.py

bind to a session

---

mita/async.py
mita/tasks.py

This fixes the problem with the models not working. Removes the ugly crutch in the shared_task

Init model

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

jessie does not have curl and omg lets just use wget

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

jessie YUUUUUGE needs the jessie tag

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

I give up. Install curl on jessie

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

install curl for wheezy machines too

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2
mita/providers/openstack.py

fix incorrect 'size' names for OVH

---

mita/providers/openstack.py

log information about created or not created node

---

mita/async.py

check for orphaned nodes and prune with celery

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This corresponds to a change in the ceph-build-pull-requests
job to request a rebootable node
Signed-off-by: Dan Mick <dan.mick@redhat.com>

Add 'rebootable' tag to all nodes except 'unique'

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

fix typo in centos7 label for ceph-ansible prs

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

add a xenial configuration for ceph-ansible

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

install and link python2.7

---

mita/tests/conftest.py

Signed-off-by: Dan Mick <dan.mick@redhat.com>

Explain that tests/conftest.py is a py.test plugin

---

deploy/playbooks/local_deploy.yml

add a local_deploy for jenkins

---

mita/providers/openstack.py

By setting a timeout when creating a node.
This would not prevent it from adding the node to mita's database, allowing it to be pruned later.

catch a probable timeout when creating a node

---

mita/async.py

do not remove a node that failed to get removed from the provider

---

mita/async.py

async: if node is not found in cloud provider, continue to the next one

---

mita/async.py
mita/tests/unit/test_util.py
mita/util.py

robust "find job name from jenkins url"

---

mita/checks.py
mita/controllers/health.py
mita/controllers/root.py
mita/tests/controllers/test_health.py

The idea is to have a nagios check hit this endpoint to verify database connection and celery/rabbitmq health.

adds a health check endpoint at /health/

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

all nodes should only have one executor

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible: update prod_nodes to new image names and labels as prod

---

mita/tests/unit/test_util.py
mita/util.py

This may cause a job to be stuck, so attempt to detect it and parse it like any other reason.

detect 'node has no label' as a stuck reason

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible: add python3 label

---

mita/providers/openstack.py
mita/tests/__init__.py
mita/tests/test_functional.py
mita/tests/unit/test_providers.py

make it a bit more robust when trying to remove a node from the provider

Destroy node check

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible all xenial now

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible: add actual python3 labels to the prado urls

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible: add 'stretch' for newer debian builds

---

mita/providers/openstack.py

providers: openstack should tell us when an image is not available

---

mita/providers/openstack.py

providers openstack upgrade made node.state checks change

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

deploy: Fix labels for centos libvirt slaves

---

mita/async.py

Fixes: http://tracker.ceph.com/issues/22289
We could try a nicer approach with a decorator, but this is easy enough.

async: when a db has an invalid request error raised, rollback the transaction and return

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

ansible: make prod_nodes apt-get update before attempting to install anything

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

prod_nodes.py: Add missing label to API call URL

---

deploy/playbooks/roles/common/tasks/main.yml

deploy: Redeploy app on every play

---

deploy/playbooks/roles/common/tasks/main.yml

prod config uses src directory, install with editable.

Fix mita install with editable

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

prod_nodes: Add leap15 definition for Opensuse slave support

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This is to help make prado py3 ready.  See https://github.com/ceph/prado/pull/27

prod_nodes: Install ansible from system package

---

deploy/playbooks/roles/common/templates/prod_provider.py.j2

OVH reached out and asked that we move to a different region to alleviate the strain on SBG1.

Use SBG5 region

---

deploy/playbooks/roles/common/templates/prod_provider.py.j2

deploy: use the keystone v3 API for authentication

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

Whoops this has been broken for months

prod_nodes: Install epel before ansible on ALL centos slaves

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This will be a new variable in the slave.yml playbook that will install libvirt-related packages

prod_nodes: Add libvirt=true variable
