ceph/mita

deploy/playbooks/roles/common/templates/prod.py.j2
mita/controllers/nodes.py

Without this the tasks were not actually committing to the database which was resulting in many duplicate slaves being created.

add the TransactionHook to the prod configuration

---

mita/tests/unit/test_util.py
mita/util.py

If the key (name) is not present we will check for anything that matches. Adds a test to verify this behavior

Node fallback

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

If these do not match mita will not be able to find the type of node to
create when a node of this type is offline.

the node name given to prado must match the key in the node config

---

mita/async.py
mita/controllers/nodes.py
mita/tests/functional/controllers/test_nodes.py

This also adds in a endpoint at api/nodes/<uuid>/active that the
check_idling async task will call to mark a node as active.

check the jenkins api to see if a node is idle before removing it

---

mita/controllers/nodes.py
mita/exceptions.py
mita/providers/openstack.py
mita/tests/functional/controllers/test_nodes.py
mita/tests/test_units.py
mita/tests/unit/test_providers.py

By raising and catching a new exception: `CloudeNodeNotFound`

fix IndexError issues

---

mita/controllers/nodes.py
mita/models/nodes.py
mita/util.py

The cloud name of a jenkins slave and the name it uses in the jenkins UI are different. Make sure we're using the correct name when deleting the slave from jenkins.

properly remove slaves from jenkins when an instance is destroyed

---

mita/util.py

This will prevent mita from breaking horribly when a node is not found in Jenkins.
Currently tests are broken because of the `connections.py` addition, will fix those next.

do not break when a node cannot be found

---

deploy/playbooks/roles/common/templates/prod.py.j2

It is a (naive) attempt to prevent double lines in production logs. Even if it does not fix that problem it is still a good idea not to have ascii chars in prod logs

do not use color output in production logs

---

mita/async.py

This just prints way too much into the log and it's not very helpful for
normal situations.

remove noisy logging in the check_idling task

---

mita/providers/openstack.py

OVH uses a non-standard state to indicate volume availability, the
integer 3.
If we raise a RuntimeError here the mita process never finishes and we
get multiple images created.

do not raise a RuntimeError if the volume is not available

---

mita/async.py
mita/tasks.py

We need this so that the celery worker that runs mita.async can see the
tasks we put into mita.tasks.

include mita.tasks into the celery app in mita.async

---

mita/async.py

prevent breakage when WHY is None from the API

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

These nodes were always meant to be used exclusively by the
ceph-ansible-pull-requests job. Making the labels this specific will
ensure that no other jobs pick up these nodes, which has been trouble in
the past.

change the 'unique' nodes to be ceph-ansible-pull-requests specific

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This will allow to use Ubuntu Trusty as the main distro for pbuilder, that will be chosen for all DEB builds (e.g. xenial, jessie, etc...)
Depends on: https://github.com/ceph/ceph-build/pull/370

create a trusty pbuilder that provides for all DEB ceph builders

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

Because I couldn't get the combination filter to work out. This will have a "trusty" machine that only provides the "xenial" label. As it was before (providing labels for other distros) it would get picked up by other jobs requiring other distro versions (e.g. 'trusty').
It also disables the Jessie image and provides a 'trusty-pbuilder' one instead.

jessie and xenial pbuilder configurations

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

The "python" package contains `/usr/bin/python`. Install it and avoid the symlink.

install "python" to get /usr/bin/python on xenial

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This patch aims at creating a new type of node. It is based on xenial and
provides all the packages required to build ceph or edeploy images.

prod_nodes: Adding ceph-builders-xenial support

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

When labels are featuing dashes, it triggers the following exception :
File "/opt/mita/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
worker.init_process()
File "/opt/mita/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
self.load_wsgi()
File "/opt/mita/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
self.wsgi = self.app.wsgi()
File "/opt/mita/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/opt/mita/local/lib/python2.7/site-packages/pecan/commands/serve.py", line 196, in load
return deploy(self.cfgfname)
File "/opt/mita/local/lib/python2.7/site-packages/pecan/deploy.py", line 9, in deploy
return load_app(config)
File …

prod_nodes: Changing dashes by underscores

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This commit is about moving the actual Ubuntu hosts to the ceph-builders image
type.
This move shall provide a faster build by providing pre-installed build requires & the xfs support.

prod_nodes: Moving Ubuntu hosts to ceph-builders images

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This patch is about using the ceph-builders image (which is similar to the
ubuntu ones) for the Centos builds

prod_nodes: Using ceph-builders-C7.2-1.0.1 instead of Centos 7

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This change does for the same price a switch to a local ssd with no raid
instead of a redunded rbd. That will speedup things while we don't care about
the redunduncy.

prod_nodes: Switching from hg-30 to hg-30-ssd

---

mita/tests/unit/test_util.py
mita/util.py

When a 'node label' is offline, it can contain more than one label. This change tries the more common single label approach falling back to multiple labels

Muli label sometimes

---

mita/controllers/nodes.py

This lowers the waiting time from 8 minutes to 4 to create a new node, and gets the idle time pushed to 20 minutes (vs. 10)

create nodes more frequently and keep them longer

---

mita/async.py
mita/controllers/nodes.py

These changes will keep a tally for how many stuck jobs are in Jenkins, vs assuming just 1.
With the count, it will then fire up as many nodes as needed, but just as long there aren't as many already requested to the provider in the past N (6 minutes at the moment) minutes

improve behavior when there is sudden high demand 

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

We don't actually needs these as we have pbuilder nodes that
build packages for us. These nodes also take a very long time
to provision, so we don't want other jobs to mistakenly use them if
they've only specified "small" as the label.

disable wheezy_small, wheezy_huge and jessie_small nodes

---

mita/providers/openstack.py

With this patch provider.openstack._wait_until_volume_available will
actually wait until the volume is ready to be attached.

fixes a bug where instances launch without attached volumes

---

mita/async.py

This fixes a longstanding issue with OVH where mita requests a node to
be destroyed, OVH ACKs, but since the removal happens asynchronously,
there are times where the nodes sticks around. With this change we are
only removing it from the database when the API reports it is no longer
there.

async: remove node from db only when it isn't available in the API

---

mita/async.py

async: correctly list providers by converting pecan conf to dict

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This is now the default node type used by any jobs that
require vagrant and libvirt. We want this so we can upgrade
to the version of libvirt available in 16.10.

config: adds a ceph_ansible_pr_yakkety node type

---

mita/async.py
requirements.txt

When deployed to a fresh xenial vm we saw this error in the
celery logs:
Received and deleted unknown message.  Wrong destination?!?
See: https://github.com/celery/celery/issues/3675

do not use librabbitmq and use pyamqp

---

mita/controllers/nodes.py
mita/tests/conftest.py
mita/tests/functional/controllers/test_nodes.py

Explained in detail in commit 3c47df8 but basically, by talking to jenkins before the cloud and ensuring the node is really idle *at that time*, reduces the opportunity for it to be deleted while it is being picked up by a job. Like here:
Building remotely on 213.32.31.177+ceph_ansible_pr_zesty__81c41988-9ceb-40fc-a17fd6a5c3424681 (libvirt python3 ceph_ansible_pr_zesty vagrant) in workspace /home/jenkins-build/build/workspace/ceph-ansible-prs-luminous-ansible2.3-bluestore_docker_dedicated_journal
FATAL: java.io.IOException: Unexpected termination of the channel
java.io.EOFException

Faster idle node removal

---

mita/tests/unit/test_util.py
mita/util.py

Jenkins loves to do this. Mita doesn't really decode to ascii everywhere, and python-jenkins uses `locals()` so we must sanitize this before passing them around.
Fixes: https://bugs.launchpad.net/python-jenkins/+bug/1775176

guard against unicode labels

---

mita/async.py

Fixes issue #129 (at least partially)

async: catch JenkinsException not NotFoundException which is not used at all

---

mita/tests/unit/test_util.py
mita/util.py

Otherwise it fails to parse properly when Jenkins returns them as seen on issue #129 :+1: 
```
[2019-08-13 19:46:04,394: INFO/ForkPoolWorker-3] found stuck task with name: ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=huge [2019-08-13 19:46:04,394: INFO/ForkPoolWorker-3] reason was: Waiting for next available executor on ‘huge&&x86_64&&bionic’ [2019-08-13 19:46:04,395: WARNING/ForkPoolWorker-3] invalid syntax (<unknown>, line 1) [2019-08-13 19:46:04,395: WARNING/ForkPoolWorker-3] unable to match: ‘huge&&x86_64&&bionic’
--
```
In this case, the single quotes are actually utf-8 chars 2018 and 2019 respectively. By removing them like we do in other places, we ensure that these will go through cleanly.
The unit test added verified the problem. After making …

remove unicode chars from helper util

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

For now, we want make check to only run on Bionic because:
1) We expect it to have python2 and python3 installed
2) All branches should build and test on bionic (but not any other distro)

prod_nodes: Create node template for pure Bionic slaves

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

Installing python2 is needed for the jenkins_node library to run.  The symlink is needed because of `/usr/bin/env python` at the top of the library file.  Note the symlink is removed after the ansible playbook runs.
The `centos8-cloud` image is a qcow2 I built using `virt-builder` then uploaded to Openstack.
`virt-builder -v centos-8.0 --install cloud-init,curl,tar,cloud-utils-growpart,yum,python3,python2,python3-libselinux,libselinux-devel,python2-libs,selinux-policy-devel,createrepo,epel-release,java-1.8.0-openjdk,git,python3-virtualenv,libtool,autoconf,redhat-lsb-core,automake,cmake,binutils,bison,flex,gcc,gcc-c++,gettext,libtool,make,patch,pkgconfig,redhat-rpm-config,rpm-build,rpmdevtools,openssl-devel,libffi-devel --format qcow2 --selinux-relabel`
Signed-off-by: David Galloway …

prod_nodes: Add template for CentOS8 cloud image

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

The version of ansible available to Xenial is 2.0.0.2 which is too old for our playbooks

prod_nodes: Add ansible ppa

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

They reached out to me asking me to stop using the hg-* flavors due to lack of systems that could support them.
We tried to switch to these along with a different region a year or two ago but they didn't have capacity.  I've been assured they have capacity now.

Use new OVH instance flavors

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

This is actually a pre-baked cloud image I ran `slave.yml` against except for the `jenkins_node` task.
For whatever reason, dnf transactions were taking FOREVER during cloud-init and the setup would timeout.  I confirmed this cloud image along with mita changes is working now though.

Use official CentOS 8.1 cloud image

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

-flex instance flavor has 50GB.  Regular c2-30 has 200GB.  Specs are the same otherwise.  ceph-ansible jobs were running out of space though so we need c2-30.

prod_nodes: Don't use -flex flavors

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

Ansible is in epel so they need epel first.  This must have been broken since https://github.com/ceph/mita/commit/09171338ad09f49333edd21caf8a4f300f9c550f

prod_nodes: Install epel on centos&&small before ansible

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

I ran some stats gathering on shaman and discovered the CentOS7 braggi builders were extremely underused.  So I reimaged 3 of them to CentOS8.  Then, yesterday, Yuri had a bunch of PR testing to do for the next Nautilus release which involved a lot of CentOS7 builds needing to be created.  I know we are trying to lessen our OVH usage but I think CentOS7 is the best distro for us to dynamically spin up nodes for since it will be the least used of them (Ubuntu/CentOS8) all.

prod_nodes: Create centos7_gigantic node

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

I got rid of the slave_libvirt playbook when I combined all playbooks in https://github.com/ceph/ceph-build/pull/1573.
I didn't actually push that change to prado until a couple weeks ago so this hasn't been broken for that long but long enough to be bad and expensive :(

prod_nodes: s/slave_libvirt/slave

---

deploy/playbooks/roles/common/templates/prod_nodes.py.j2

deploy: Unpin centos7 nodes. Use latest OVH-provided Centos 7.
